name: passwordfield
description: A simple and easy to use Passwordfield Widget to add a password Textfield to your Flutter project hassle free.
version: 0.2.0
homepage: https://github.com/maheshmnj/passwordfield/
repository: https://github.com/maheshmnj/passwordfield/
issue_tracker: https://github.com/maheshmnj/passwordfield/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.1
